import * as React from 'react';
import { api, Link, loginDestination, useApp } from './context';
import { Alert, Button, EmptyState, ErrorMessage, Field, Icon, Loading, Status } from './ui';
import { formatDate, SERVICE_NAMES } from './booking';
import type { Reservation } from './types';

export function AccountGuard({ children, internal = false, corporate = false }: { children: React.ReactNode; internal?: boolean; corporate?: boolean }) {
  const { user, authLoading, authError, refreshUser, t, path } = useApp();
  if (authLoading) return <div className="inner-page container"><Loading /></div>;
  if (authError) return <div className="inner-page container"><Alert type="error">{t('Your session could not be checked. Please retry.', 'No se pudo comprobar tu sesión. Vuelve a intentarlo.')}<Button tone="secondary" onClick={() => void refreshUser()}>{t('Retry', 'Reintentar')}</Button></Alert></div>;
  if (!user) return <div className="inner-page container"><EmptyState title={t('Your personal space awaits.', 'Tu espacio personal te espera.')} action={<Link className="button button-primary" href={loginDestination(path)}>{t('Sign in', 'Iniciar sesión')}<Icon name="arrow" /></Link>}>{t('Sign in to see the requests associated with your account.', 'Inicia sesión para consultar las solicitudes asociadas a tu cuenta.')}</EmptyState></div>;
  if (internal && !user.roles.includes('ASCENTA_ADMIN')) return <div className="inner-page container"><EmptyState title={t('Internal access only.', 'Solo acceso interno.')} action={<Link className="button button-primary" href="/dashboard">{t('My account', 'Mi cuenta')}</Link>}>{t('Operations access requires an ASCENTA administrator account.', 'El acceso a operaciones requiere una cuenta de administrador de ASCENTA.')}</EmptyState></div>;
  if (corporate && !user.roles.some(role => role === 'CORPORATE_ADMIN' || role === 'CORPORATE_BOOKER')) return <div className="inner-page container"><EmptyState title={t('Business, with a personal touch.', 'Empresas, con atención personal.')} action={<Link className="button button-primary" href="/business">{t('Explore business travel', 'Conocer viajes corporativos')}</Link>}>{t('Corporate access is not enabled for this account. Your personal journeys remain available in My account.', 'El acceso corporativo no está habilitado para esta cuenta. Tus viajes personales siguen disponibles en Mi cuenta.')}</EmptyState></div>;
  return <>{children}</>;
}
export function PortalShell({ children, active = 'journeys', internal = false }: { children: React.ReactNode; active?: string; internal?: boolean }) {
  const { user, t, logout } = useApp();
  const [error, setError] = React.useState<unknown>(null);
  const [busy, setBusy] = React.useState(false);
  const corporate = user?.roles.some(role => role === 'CORPORATE_ADMIN' || role === 'CORPORATE_BOOKER');
  return <section className="portal-page container" data-nav-theme="light"><div className="portal-layout"><aside className="portal-sidebar"><div className="sidebar-person"><div className="profile-badge">{user?.displayName.slice(0, 1).toUpperCase()}</div><small>{t('WELCOME', 'BIENVENIDO')}</small><strong>{user?.displayName}</strong><span>{user?.email}</span></div>
    <nav className="portal-nav" aria-label={t('Account navigation', 'Navegación de cuenta')}><Link className={!internal && active === 'journeys' ? 'active' : ''} aria-current={!internal && active === 'journeys' ? 'page' : undefined} href="/dashboard"><Icon name="calendar" />{t('My journeys', 'Mis viajes')}</Link><Link className={active === 'profile' ? 'active' : ''} aria-current={active === 'profile' ? 'page' : undefined} href="/account"><Icon name="shield" />{t('Account & security', 'Cuenta y seguridad')}</Link>
    {corporate && <Link className={active === 'corporate' ? 'active' : ''} aria-current={active === 'corporate' ? 'page' : undefined} href="/corporate"><Icon name="building" />{t('Business account', 'Cuenta empresarial')}</Link>}
    {user?.roles.includes('ASCENTA_ADMIN') && <Link className={internal ? 'active' : ''} aria-current={internal ? 'page' : undefined} href="/admin"><Icon name="users" />{t('Operations', 'Operaciones')}</Link>}
    <Link href="/help"><Icon name="info" />{t('Help', 'Ayuda')}</Link></nav>
    <Button tone="quiet" className="signout" busy={busy} onClick={async () => { setBusy(true); setError(null); try { await logout(); } catch (reason) { setError(reason); } finally { setBusy(false); } }}><Icon name="logout" />{t('Sign out', 'Cerrar sesión')}</Button><ErrorMessage error={error} /></aside><div className="portal-main">{children}</div></div></section>;
}
export function JourneyCard({ row, children }: { row: Reservation; children?: React.ReactNode; onChange?: () => void }) {
  const { t, lang } = useApp();
  const [expanded, setExpanded] = React.useState(false);
  const service = SERVICE_NAMES[row.serviceTypeCode as keyof typeof SERVICE_NAMES];
  return <article className="request-card"><div className="request-card-head"><div><small className="request-reference">{row.reference}</small><span className="request-date">{formatDate(row.scheduledAt, row.scheduledTimeZone, lang)}</span></div><Status status={row.status} /></div>
    <div className="request-card-body"><div className="request-route"><p><span />{row.pickupAddress}</p><p><span />{row.destinationAddress || t('Hourly itinerary', 'Itinerario por horas')}</p></div><div className="request-meta"><span><Icon name="car" size={17} />{row.vehicleClassCode.replaceAll('_', ' ')}</span><span><Icon name="users" size={17} />{row.passengerCount}</span><span>{service ? t(service[0], service[1]) : row.serviceTypeCode}</span>{row.durationHours !== undefined && <span><Icon name="clock" size={17} />{row.durationHours} h</span>}</div>
    {expanded && <div className="request-extra"><dl><div><dt>{t('Passenger', 'Pasajero')}</dt><dd>{[row.passengerName, row.passengerPhone, row.passengerEmail].filter(Boolean).join(' · ') || '—'}</dd></div><div><dt>{t('Pickup time zone', 'Zona horaria de recogida')}</dt><dd>{row.scheduledTimeZone}</dd></div>{row.organizationId && <div><dt>{t('Organization reference', 'Referencia de organización')}</dt><dd>{row.organizationId}</dd></div>}{row.requesterName && <div><dt>{t('Requested by', 'Solicitado por')}</dt><dd>{row.requesterName}{row.requesterEmail ? ` · ${row.requesterEmail}` : ''}</dd></div>}{row.notes && <div><dt>{t('Notes and additional journey details', 'Notas y datos adicionales del viaje')}</dt><dd>{row.notes}</dd></div>}</dl></div>}
    <div className="request-actions"><Button tone="quiet" onClick={() => setExpanded(!expanded)} aria-expanded={expanded}>{expanded ? t('Hide details', 'Ocultar detalles') : t('Journey details', 'Detalles del viaje')}<Icon name="chevron" size={16} /></Button></div>{children}</div></article>;
}
function exportRequests(rows: Reservation[]) {
  const cell = (value: string | number | undefined) => { const text = String(value ?? ''); return `"${(/^[=+\-@\t\r]/.test(text) ? `'${text}` : text).replaceAll('"', '""')}"`; };
  const lines = [['Reference', 'Status', 'Pickup', 'Destination', 'Pickup instant', 'Time zone', 'Passengers', 'Passenger', 'Notes'], ...rows.map(row => [row.reference, row.status, row.pickupAddress, row.destinationAddress, row.scheduledAt, row.scheduledTimeZone, row.passengerCount, row.passengerName, row.notes])];
  const url = URL.createObjectURL(new Blob(['\ufeff' + lines.map(row => row.map(cell).join(',')).join('\r\n')], { type: 'text/csv;charset=utf-8' }));
  const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'ascenta-authorized-requests.csv'; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}
export function JourneysPage({ corporate = false }: { corporate?: boolean }) { const { user } = useApp(); return <AccountGuard corporate={corporate}><JourneyList key={user?.id} corporate={corporate} /></AccountGuard>; }
function JourneyList({ corporate }: { corporate: boolean }) {
  const { t, user, runtime } = useApp();
  const [rows, setRows] = React.useState<Reservation[]>([]);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState<unknown>(null);
  const [filter, setFilter] = React.useState('active');
  const [query, setQuery] = React.useState('');
  const refresh = React.useCallback(async () => { setLoading(true); setError(null); try { setRows(await api('/requests')); } catch (reason) { setRows([]); setError(reason); } finally { setLoading(false); } }, []);
  React.useEffect(() => { const frame = requestAnimationFrame(() => { void refresh(); }); return () => cancelAnimationFrame(frame); }, [refresh, user?.id]);
  const visible = rows.filter(row => (!corporate || Boolean(row.organizationId)) && (filter === 'all' || (filter === 'active' ? !['COMPLETED', 'CANCELLED'].includes(row.status) : ['COMPLETED', 'CANCELLED'].includes(row.status))) && `${row.reference} ${row.pickupAddress} ${row.destinationAddress ?? ''} ${row.passengerName ?? ''}`.toLowerCase().includes(query.toLowerCase()));
  return <PortalShell active={corporate ? 'corporate' : 'journeys'}><div className="portal-heading"><div><p className="eyebrow">{corporate ? t('YOUR ORGANIZATION', 'TU ORGANIZACIÓN') : t('YOUR PERSONAL SPACE', 'TU ESPACIO PERSONAL')}</p><h1>{corporate ? t('Business journeys.', 'Viajes empresariales.') : t('Your journeys.', 'Tus viajes.')}</h1><p>{t('Each request. Every detail. The actual status.', 'Cada solicitud. Cada detalle. El estado real.')}</p></div><Link className="button button-primary" href="/booking">{t('Plan a journey', 'Planificar viaje')}<Icon name="arrow" /></Link></div>
    {runtime?.reviewMode && <Alert>{t('Demo environment. Requests are saved while the local service is running.', 'Entorno de demostración. Las solicitudes se guardan mientras el servicio local está activo.')}</Alert>}
    {corporate && <p>{t('This view includes the organization requests your account is authorized to access.', 'Esta vista incluye las solicitudes de organizaciones que tu cuenta tiene autorización para consultar.')}</p>}
    <div className="portal-toolbar"><div className="portal-tabs">{[['active', t('Upcoming / open', 'Próximos / abiertos')], ['history', t('History', 'Historial')], ['all', t('All', 'Todos')]].map(([value, label]) => <button key={value} aria-pressed={filter === value} onClick={() => setFilter(value)}>{label}</button>)}</div><Button tone="quiet" disabled={loading} onClick={() => void refresh()}><Icon name="refresh" size={17} />{t('Refresh', 'Actualizar')}</Button></div><div className="field-grid"><Field id="journey-search" label={t('Find a journey', 'Buscar viaje')}><input id="journey-search" type="search" value={query} onChange={event => setQuery(event.target.value)} placeholder={t('Reference, location or passenger', 'Referencia, lugar o pasajero')} /></Field>{corporate && <div className="page-actions"><Button tone="secondary" disabled={!visible.length} onClick={() => exportRequests(visible)}><Icon name="download" />{t('Export this selection', 'Exportar selección')}</Button></div>}</div>
    <ErrorMessage error={error} />{loading ? <Loading /> : error ? null : !visible.length ? <EmptyState title={t('A little space for what’s next.', 'Espacio para tu próximo viaje.')} action={<Link className="button button-secondary" href="/booking">{t('Start a request', 'Comenzar solicitud')}</Link>}>{t('There are no journeys matching this view.', 'No hay viajes que coincidan con esta vista.')}</EmptyState> : <div className="request-list">{visible.map(row => <JourneyCard key={row.id} row={row} />)}</div>}
  </PortalShell>;
}
export function ProfilePage() { return <AccountGuard><Profile /></AccountGuard>; }
function Profile() {
  const { t, user } = useApp();
  return <PortalShell active="profile"><div className="portal-heading"><div><p className="eyebrow">{t('YOUR DETAILS', 'TUS DATOS')}</p><h1>{t('Account & security.', 'Cuenta y seguridad.')}</h1><p>{t('Only what your account needs.', 'Solo lo que tu cuenta necesita.')}</p></div></div><section className="form-panel account-form"><h2>{t('Personal information', 'Información personal')}</h2><Field label={t('Full name', 'Nombre completo')} id="profile-name"><input id="profile-name" autoComplete="name" value={user?.displayName ?? ''} readOnly /></Field><Field label={t('Account email', 'Correo de la cuenta')} id="profile-email"><input id="profile-email" type="email" value={user?.email ?? ''} readOnly /></Field><p className="expiry-note"><Icon name={user?.emailVerified ? 'check' : 'info'} />{user?.emailVerified ? t('Email verified', 'Correo verificado') : t('Verification pending', 'Verificación pendiente')}</p><Alert>{t('Profile editing and password recovery are not available yet.', 'La edición del perfil y la recuperación de contraseña aún no están disponibles.')}</Alert><div className="form-actions"><Button disabled>{t('Save changes', 'Guardar cambios')}</Button></div><hr /><h2>{t('Account security', 'Seguridad de la cuenta')}</h2><p>{t('Sign out from the account menu to close your current session.', 'Cierra sesión desde el menú de tu cuenta para terminar tu sesión actual.')}</p><Button tone="secondary" disabled>{t('Reset my password', 'Restablecer mi contraseña')}</Button></section></PortalShell>;
}
