packages:
  - "apps/*"
  - "packages/*"

overrides:
  deepmerge-ts: 8.0.0
  ip-address: 10.7.1
  mariadb: 3.4.7
  mysql2: 3.23.1

allowBuilds:
  "@prisma/engines": true
  esbuild: true
  prisma: true
